# Generated by Django 6.1.1 on 2026-09-27 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Restaurante')),
                ('slug', models.SlugField(help_text='Ex: pizzaria-do-mario', unique=True, verbose_name='Slug / Subdomínio URL')),
                ('whatsapp_number', models.CharField(help_text='DDD + Número sem espaços', max_length=20, verbose_name='WhatsApp para Pedidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
