# Generated by Django 6.1.1 on 2026-10-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Pedido Mínimo'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Segunda-feira'), ('1', 'Terça-feira'), ('2', 'Quarta-feira'), ('3', 'Quinta-feira'), ('4', 'Sexta-feira'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=1, verbose_name='Dia da Semana')),
                ('opening_time', models.TimeField(verbose_name='Abertura')),
                ('closing_time', models.TimeField(verbose_name='Fechamento')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado o dia todo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='tenants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('category', models.CharField(choices=[('ONLINE', 'Pagamento online'), ('DELIVERY', 'Pagamento na entrega')], max_length=10, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo na loja')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='tenants.restaurant')),
            ],
        ),
    ]
