# Generated by Django 6.1.1 on 2026-09-28 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Entrega (R$)')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='tenants.restaurant')),
            ],
            options={
                'verbose_name': 'Taxa de Entrega',
                'verbose_name_plural': 'Taxas de Entrega',
            },
        ),
    ]
