# Generated by Django 6.1.1 on 2026-09-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_deliveryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='PIX', max_length=50, verbose_name='Forma de Pagamento'),
        ),
    ]
